# Generated by Django 5.0.4 on 2024-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
