# Generated by Django 5.0.4 on 2024-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_listened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('id',)},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['id'], name='api_song_id_5a3a7c_idx'),
        ),
    ]
