# Generated by Django 5.0.4 on 2024-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('id',)},
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['id'], name='api_album_id_5284e6_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['id'], name='api_artist_id_0571d6_idx'),
        ),
    ]
